import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css";
import { AppProps } from "next/app";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sudoku Game",
  description: "Generated by create next app",
};

export default function App({
  Component, pageProps
}: AppProps) {
  const currentDate = new Date();
  const currentYear = currentDate?.getFullYear();
  return (

    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Component {...pageProps} />
        <div className="fixed bottom-0 mx-auto w-full bg-black text-white text-center">
          ©{currentYear} All Rights Reserved.
        </div>
      </body>
    </html>

  );
}
